spring:
  jpa:
#    콘솔에 sql 출력
    show-sql: true
#    출력되는 sql을 보기 좋게 포맷팅
    properties:
      hibernate:
        format_sql: true
#      스프링 부트가 데이터소스 초기화(data.sql 실행)을 JPA 엔티티 테이블이 생성된 이후로 지연.
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

#issuer : 토큰 발급자
#secret_key : JWT 서명을 위한 비밀  키.토큰의 생성 및 검증 과정에서 사용
jwt:
  issuer: dndbs91@gmail.com
  secret_key: study-springboot
